// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nazGJzlQrUSPmsTWZmGDp0Ey7pD6-Rc',
    appId: '1:521663665160:web:2507fa05155bb501ebedbd',
    messagingSenderId: '521663665160',
    projectId: 'vocal-flip',
    authDomain: 'vocal-flip.firebaseapp.com',
    storageBucket: 'vocal-flip.firebasestorage.app',
    measurementId: 'G-42LMYYJ5M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiTSs8VY34uzWaKWVh0rWiYivD3K9E1Bc',
    appId: '1:521663665160:android:4f0d2f5f6193226bebedbd',
    messagingSenderId: '521663665160',
    projectId: 'vocal-flip',
    storageBucket: 'vocal-flip.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_nazGJzlQrUSPmsTWZmGDp0Ey7pD6-Rc',
    appId: '1:521663665160:web:d2f593056853a8beebedbd',
    messagingSenderId: '521663665160',
    projectId: 'vocal-flip',
    authDomain: 'vocal-flip.firebaseapp.com',
    storageBucket: 'vocal-flip.firebasestorage.app',
    measurementId: 'G-S29JMGKVX3',
  );

}